=== linhongcun/aoe2-analyzer/src/content/schema/data-civs.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://linhongcun.github.io/aoe2-analyzer/schema/data-civs.json",
  "title": "AoE2 civs data",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "en": {
        "$ref": "common.defs.json#/$defs/nonEmptyString"
      },
      "zh": {
        "$ref": "common.defs.json#/$defs/nonEmptyString"
      },
      "ty": {
        "type": "array",
        "items": {
          "type": "string",
          "enum": ["cav", "arch", "inf", "naval", "monk", "siege", "def", "eco"]
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "desc": {
        "type": "string"
      },
      "uu": {
        "type": "string"
      },
      "ct": {
        "type": "string"
      },
      "it": {
        "type": "string"
      },
      "bon": {
        "type": "array",
        "items": {
          "$ref": "common.defs.json#/$defs/sourceText"
        }
      },
      "bonEn": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "tb": {
        "type": "string"
      },
      "tbEn": {
        "type": "string"
      },
      "s": {
        "type": "array",
        "items": {
          "type": "number",
          "minimum": 0,
          "maximum": 10
        },
        "minItems": 8,
        "maxItems": 8
      },
      "fl": {
        "type": "number"
      },
      "pk": {
        "type": "number"
      },
      "op": {
        "type": "string"
      },
      "py": {
        "type": "string",
        "pattern": "^[a-z]*$"
      },
      "pyi": {
        "type": "string",
        "pattern": "^[a-z]*$"
      }
    },
    "required": ["en", "zh", "ty", "desc", "uu", "ct", "it", "bon", "bonEn", "tb", "tbEn", "s", "fl", "pk", "op", "py", "pyi"],
    "additionalProperties": false
  },
  "minItems": 1
}

=== linhongcun/aoe2-analyzer/src/data/civs.json
[{"en":"Armenians","zh":"亚美尼亚","ty":["inf","naval"],"desc":"步兵和海军文明","uu":"复合弓箭手 (步弓手)，牧师战士 (步兵)（Composite Bowman (Foot Archer), Warrior Priest (Infantry)）","ct":"奇里乞亚舰队 (爆破船爆炸范围 +20%；箭船系和德罗蒙战舰射程 +1)｜Cilician Fleet","it":"费雷特斯 (除长矛兵系以外的步兵生命值 +30；牧师战士治疗速度 +100%)｜Fereters","bon":["骡车费用 -25%","骡车科技效率 +40%","可提前一个时代获得长矛兵系和民兵系升级 (武士除外)","建造首座强化教堂可免费获得一件圣物","箭船系和德罗蒙战舰可额外发射一颗炮弹"],"bonEn":["Mule Carts cost -25%","Mule Cart technology effects +40%","Spearman- and Militia-line upgrades (except Man-at-Arms) available one age earlier","First Fortified Church receives a free Relic","Galley-line and Dromons fire an additional projectile"],"tb":"步兵视野 +2","tbEn":"Infantry +2 line of sight","s":[3,6,9,7,6,5,7,8],"fl":8,"pk":5,"op":"民兵/长矛压制 -> 城堡复合弓 + 冠军步兵","py":"yameiniya","pyi":"ymny"},{"en":"Aztecs","zh":"阿兹特克","ty":["inf","monk"],"desc":"步兵和僧侣文明","uu":"豹勇士 (步兵)（Jaguar Warrior (Infantry)）","ct":"掷矛器 (掷矛手攻击力 +1，射程 +1)｜Atlatl","it":"荣冠战争 (步兵攻击力 +4)｜Garland Wars","bon":["初始黄金 +50","村民携带量 +3","军事单位训练速度 +15%","研究一项修道院科技后僧侣的生命值 +5"],"bonEn":["Start with +50 gold","Villagers carry +3","Military Units train +15% faster","Monks gain +5 HP for each researched Monastery technology"],"tb":"圣物产生的黄金 +33%","tbEn":"Relics generate +33% gold","s":[1,6,9,7,5,7,10,5],"fl":8,"pk":3,"op":"民兵+鹰侦察兵骚扰 -> 城堡鹰战士/弓手 -> 帝王美洲豹/武士","py":"aziteke","pyi":"aztk"},{"en":"Bengalis","zh":"孟加拉","ty":["cav","naval"],"desc":"象兵和海军文明","uu":"战车 (骑射手)（Ratha (Mounted Archer)）","ct":"派 (战车和象兵单位的攻击速度 +20%)｜Paiks","it":"大乘佛教 (村民和僧侣所占人口空间 -10%)｜Mahayana","bon":["到达下一时代时，城镇中心产生 2 个村民","骑兵对掷矛手的攻击力 +2","象兵单位受到的额外伤害 -25% 并提升该单位抵抗招降的能力","僧侣近战护甲 +3/远程护甲 +3","船舰每分钟恢复 15 生命值"],"bonEn":["Town Centers spawn 2 Villagers when the next Age is reached","Cavalry +2 attack vs. Skirmishers","Elephant Units receive -25% bonus damage and are more resistant to conversion","Monks +3 melee/+3 pierce armor","Ships regenerate 15 HP per minute"],"tb":"贸易单位不仅能产生黄金，还能额外产生 10% 的食物","tbEn":"Trade Units generate +10% food in addition to gold","s":[7,6,3,6,5,5,6,8],"fl":5,"pk":7,"op":"侦察骑兵 -> 城堡战车 + 战象","py":"mengjiala","pyi":"mjl"},{"en":"Berbers","zh":"柏柏尔","ty":["cav","naval"],"desc":"骑兵和海军文明","uu":"骆驼射手 (骑射手)、标枪骑兵 (骑乘掷矛手)（Camel Archer (Mounted Archer), Genitour (Mounted Skirmisher)）","ct":"土堡 (团队的城堡工作速度 +25%)｜Kasbah","it":"马格里布骆驼 (骆驼单位每分钟恢复 15 生命值)｜Maghrebi Camels","bon":["村民在黑暗时代的移动速度 +5%，从封建时代开始 +10%","马厩单位在城堡/帝王时代的费用 -15/20%","船舰移动速度 +10%"],"bonEn":["Villagers move +5% faster in Dark Age, +10% faster starting in Feudal Age","Stable Units cost -15/20% in Castle/Imperial Age","Ships move +10% faster"],"tb":"从城堡时代开始，靶场提供标枪骑兵","tbEn":"Genitour available at the Archery Range starting in Castle Age","s":[8,7,3,7,4,4,5,7],"fl":7,"pk":7,"op":"侦察骑兵 -> 城堡骑士/骆驼射手","py":"baibaier","pyi":"bbe"},{"en":"Bohemians","zh":"波希米亚","ty":["inf","monk","siege"],"desc":"火药和僧侣文明","uu":"胡斯派战车 (攻城火药单位)、榴弹炮 (攻城火药单位)（Hussite Wagon (Siege Gunpowder Unit), Houfnice (Siege Gunpowder Unit)）","ct":"大车阵战术 (火药单位移动速度 +10%)｜Wagenburg Tactics","it":"胡斯革新 (僧侣和修道院科技消耗黄金，而不消耗食物)｜Hussite Reforms","bon":["采矿场科技免费","铁匠铺和大学的木材费用 -100","长矛兵系造成的额外伤害 +25%","狂热和圣洁会影响村民","在城堡时代可使用化学和火枪手"],"bonEn":["Mining Camp technologies free","Blacksmiths and Universities cost -100 wood","Spearman-line deals +25% bonus damage","Fervor and Sanctity affect Villagers","Chemistry and Hand Cannoneer available in Castle Age"],"tb":"市场效率 +80%","tbEn":"Markets work +80% faster","s":[2,6,8,8,7,9,9,4],"fl":6,"pk":6,"op":"弓箭/长矛 -> 城堡僧侣+手炮 -> 帝王大炮","py":"boximiya","pyi":"bxmy"},{"en":"Britons","zh":"不列颠","ty":["arch"],"desc":"步弓手文明","uu":"长弓兵 (步弓手)（Longbowman (Foot Archer)）","ct":"英皇侍卫 (步弓手和掷矛手系射程 +1；瞭望箭塔系攻击力 +2)｜Yeomen","it":"战狼号 (巨型投石机可造成爆破伤害，且准确度更高)｜Warwolf","bon":["羊倌工作速度 +25%","从城堡时代开始，城镇中心的木材费用 -50%","步弓手在城堡/帝王时代的射程 +1/+2"],"bonEn":["Shepherds work +25% faster","Town Centers cost -50% wood starting in Castle Age","Foot Archers +1/+2 range in Castle/Imperial Age"],"tb":"靶场工作速度 +10%","tbEn":"Archery Ranges work +10% faster","s":[3,10,6,7,6,6,3,6],"fl":10,"pk":3,"op":"速封建弓箭手 -> 城堡弩兵 -> 帝王长弓手","py":"buliedian","pyi":"bld"},{"en":"Bulgarians","zh":"保加利亚","ty":["cav","inf"],"desc":"步兵和骑兵文明","uu":"保加利亚骑兵 (骑兵)（Konnik (Cavalry)）","ct":"马镫 (骑兵攻击速度 +33%)｜Stirrups","it":"协议 (民兵系近战护甲 +5)｜Bagains","bon":["民兵系升级免费","铁匠铺和攻城武器厂科技的食物费用 -50%","城镇中心石料费用 -50%","在城堡时代可建造营垒"],"bonEn":["Militia-line upgrades free","Blacksmith and Siege Workshop technologies cost -50% food","Town Centers cost -50% stone","Can build Krepost in Castle Age"],"tb":"铁匠铺工作速度 +80%","tbEn":"Blacksmiths work +80% faster","s":[8,4,8,7,7,6,4,4],"fl":7,"pk":7,"op":"民兵冲 -> 城堡骑士/Konnik","py":"baojialiya","pyi":"bjly"},{"en":"Burgundians","zh":"勃艮第","ty":["cav"],"desc":"骑兵文明","uu":"马上轻装兵 (骑兵)、弗拉芒民兵 (步兵)（Coustillier (Cavalry), Flemish Militia (Infantry)）","ct":"勃艮第葡萄园 (农民不仅能产生食物，还能缓慢地产生黄金)｜Burgundian Vineyards","it":"弗拉芒革命 (将所有现有村民转变为弗拉芒民兵)｜Flemish Revolution","bon":["可提前一个时代进行经济升级并且食物费用 -40%","马厩科技费用 - 50%","在城堡时代可升级为重装骑士","火药单位攻击力 +25%"],"bonEn":["Economic upgrades available one age earlier and cost -40% food","Stable technologies cost -50%","Cavalier upgrade available in Castle Age","Gunpowder Units +25% attack"],"tb":"圣物不仅能产生黄金，还能产生食物","tbEn":"Relics generate food in addition to gold","s":[9,4,7,9,5,5,6,5],"fl":4,"pk":9,"op":"速城堡(提前农田) -> 骑士/Coustillier","py":"bogendi","pyi":"bgd"},{"en":"Burmese","zh":"缅甸","ty":["inf","monk","cav"],"desc":"步兵和骑兵文明","uu":"飞镖骑兵 (远程骑兵单位)（Arambai (Ranged Mounted Unit)）","ct":"曼尼普尔马 (骑兵对远程士兵的攻击力 +4)｜Manipur Cavalry","it":"象轿 (象兵近战护甲 +1/远程护甲 +1)｜Howdah","bon":["伐木场科技免费","步兵在封建/城堡/帝王时代的攻击力 +1/+2/+3","象兵近战护甲 +1/远程护甲 +1","修道院科技费用 -50%"],"bonEn":["Lumber Camp technologies free","Infantry +1/+2/+3 attack in Feudal/Castle/Imperial Age","Battle Elephants +1 melee/+1 pierce armor","Monastery technologies cost -50%"],"tb":"游戏开始时就能在地图上看见圣物","tbEn":"Relics visible on the map at the start of the game","s":[7,4,8,7,5,6,8,5],"fl":5,"pk":7,"op":"侦察骑兵/民兵 -> 城堡骑士+Arambai -> 战象","py":"miandian","pyi":"md"},{"en":"Byzantines","zh":"拜占庭","ty":["def","arch","naval"],"desc":"防御文明","uu":"甲胄骑兵 (骑兵)（Cataphract (Cavalry)）","ct":"希腊之火 (喷火船射程 +1；德罗蒙战舰和炮塔的爆炸范围提升)｜Greek Fire","it":"后勤学 (甲胄骑兵和瓦兰吉卫队可造成践踏伤害)｜Logistica","bon":["建筑在黑暗/封建/城堡/帝王时代的生命值 +10/20/30/40%","骆驼骑兵、掷矛手和长矛兵系的费用 -25%","城镇瞭望、城镇巡逻免费","升级到帝王时代的费用 -33%","喷火船和德罗蒙战舰的攻击速度 +25%"],"bonEn":["Buildings +10/20/30/40% HP in Dark/Feudal/Castle/Imperial Age","Camel Riders, Skirmishers and Spearman-line cost -25%","Town Watch, Town Patrol free","Advancing to Imperial Age costs -33%","Fire Ships and Dromons attack +25% faster"],"tb":"僧侣治疗速度 +100%","tbEn":"Monks heal +100% faster","s":[6,7,6,5,9,5,8,8],"fl":7,"pk":5,"op":"散兵+长矛防守 -> 城堡骆驼/重甲骑兵","py":"baizhanting","pyi":"bzt"},{"en":"Celts","zh":"凯尔特","ty":["inf","siege"],"desc":"步兵和攻城武器文明","uu":"靛蓝突袭者 (步兵)（Woad Raider (Infantry)）","ct":"堡垒 (城堡和瞭望箭塔系的攻击速度 +33%；城堡会治疗 7 格范围内的友方步兵)｜Stronghold","it":"凯尔特狂暴 (攻城武器的生命值 +40%)｜Furor Celtica","bon":["伐木工工作速度 +15%","处于凯尔特单位视野内的牲畜不会被窃取","步兵在黑暗/封建/城堡/帝王时代的移动速度 +5/10/15/20%","攻城武器攻击速度 +25%"],"bonEn":["Lumberjacks work +15% faster","Livestock animals within Celt unit line of sight cannot be stolen","Infantry moves +5/10/15/20% faster in Dark/Feudal/Castle/Imperial Age","Siege Weapons attack +25% faster"],"tb":"攻城武器厂的生产速度 +20%","tbEn":"Siege Workshops work +20% faster","s":[4,4,8,7,6,9,4,5],"fl":7,"pk":5,"op":"民兵/长矛 -> 城堡蝎子+冲车 -> 帝王投石","py":"kaierte","pyi":"ket"},{"en":"Chinese","zh":"中国","ty":["arch","naval"],"desc":"步弓手和火药文明","uu":"诸葛弩 (步弓手)、龙舟 (战船)（Chu Ko Nu (Foot Archer), Dragon Ship (Warship)）","ct":"长城 (城墙、瞭望箭塔系和炮塔的生命值 +30%)｜Great Wall","it":"火箭术 (弩炮、火箭推车和楼船攻击力 +25%；楼船可发射火箭)｜Rocketry","bon":["初始村民数 +3，但是木材 -50 且食物 -200","科技在封建/城堡/帝王时代的费用 -5/10/15%","城镇中心的视野 +7，提供的人口控件 +15","火矛兵和喷火船在城堡/帝王时代移动速度 +5/10%"],"bonEn":["Start with +3 Villagers, but -50 wood and -200 food","Technologies cost -5/10/15% in Feudal/Castle/Imperial Age","Town Centers +7 line of sight and provide +15 population space","Fire Lancers and Fire Ships move +5/10% faster in Castle/Imperial Age"],"tb":"农田的食物 +10%","tbEn":"Farms +10% food","s":[6,9,6,9,7,7,7,7],"fl":8,"pk":6,"op":"弓箭/侦察 -> 城堡诸葛弩/骑射","py":"zhongguo","pyi":"zg"},{"en":"Cumans","zh":"库曼","ty":["cav"],"desc":"骑兵文明","uu":"钦察 (骑射手)（Kipchak (Mounted Archer)）","ct":"大草原畜牧 (斥候骑兵、草原枪兵和骑射手的训练速度 +100%)｜Steppe Husbandry","it":"库曼雇佣军 (所有团队成员均可在每座城堡免费训练 5 名精锐钦察)｜Cuman Mercenaries","bon":["在封建时代可额外建造一座城镇中心","骑兵单位在封建/城堡/帝王时代的移动速度 +5/10/15%","靶场和马厩的木材费用 -75","在封建时代可使用攻城武器厂和攻城锤；在城堡时代可使用中型冲车"],"bonEn":["One additional Town Center can be built in Feudal Age","Mounted Units move +5/10/15% faster in Feudal/Castle/Imperial Age","Archery Ranges and Stables cost -75 wood","Siege Workshop and Battering Ram available in Feudal Age; Capped Ram available in Castle Age"],"tb":"木栅栏生命值 +33%","tbEn":"Palisade Walls +33% HP","s":[9,7,4,8,4,6,3,4],"fl":6,"pk":8,"op":"封建双TC速推 -> 城堡骑士/骑射","py":"kuman","pyi":"km"},{"en":"Danes","zh":"丹麦人","ty":["inf","siege"],"desc":"步兵和攻城文明","uu":"约姆斯维京 (步兵)（Jomsviking (Infantry)）","ct":"哈马思克 (步兵失去生命值时，造成更多伤害)｜Hamask","it":"北方人之怒 (投石车系和大型投石战舰的射程 +1；攻城武器和攻城战船对建筑的攻击 +40%)｜Northmen's Fury","bon":["捕鱼船和村民存放的食物 +5%","每摧毁一座建筑，抢掠其 25% 的资源费用","兵营和攻城武器厂升级花费的黄金 -66%","瓦兰吉卫队和维京长船的移动速度 +10%"],"bonEn":["Fishing Ships and Villagers drop off +5% food","Loot 25% of the resource cost of each destroyed building","Barracks and Siege Workshop upgrades cost -66% gold","Varangian Guards and Longships move +10% faster"],"tb":"攻城武器的视野 +2","tbEn":"Siege Weapons +2 line of sight","s":[3,5,9,7,5,9,4,8],"fl":7,"pk":5,"op":"民兵/长矛压制 -> 城堡 Jomsviking + 冲车/投石车推进","py":"danmairen","pyi":"dmr"},{"en":"Dravidians","zh":"达罗毗荼","ty":["inf","arch","naval"],"desc":"步兵和海军文明","uu":"乌鲁米剑士 (步兵)、楼船 (战船)（Urumi Swordsman (Infantry), Thirisadai (Warship)）","ct":"医疗部队 (象兵单位每分钟恢复 30 生命值)｜Medical Corps","it":"乌兹钢 (步兵和骑兵的攻击无视护甲)｜Wootz Steel","bon":["渔夫和捕鱼船的携带资源量 +15","升级到下一时代时获得的木材 +200","掷矛手和骑象弓兵的攻击速度 +25%","兵营科技费用 -50%","攻城武器的木材费用 -33%"],"bonEn":["Fishermen and Fishing Ships carry +15","Receive +200 wood when advancing to the next Age","Skirmishers and Elephant Archers attack +25% faster","Barracks technol
