=== linhongcun/aoe2-analyzer/src/content/schema/data-techs.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://linhongcun.github.io/aoe2-analyzer/schema/data-techs.json",
  "title": "AoE2 techs data",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "minimum": 0
      },
      "en": {
        "$ref": "common.defs.json#/$defs/nonEmptyString"
      },
      "zh": {
        "$ref": "common.defs.json#/$defs/nonEmptyString"
      },
      "type": {
        "type": "string"
      },
      "age": {
        "type": "integer",
        "minimum": 1,
        "maximum": 4
      },
      "b": {
        "type": "integer"
      },
      "pic": {
        "type": ["integer", "string"]
      },
      "pre": {
        "anyOf": [
          {
            "type": "integer",
            "minimum": 0
          },
          {
            "type": "null"
          }
        ]
      },
      "cost": {
        "$ref": "common.defs.json#/$defs/cost"
      },
      "rt": {
        "type": "number"
      },
      "desc": {
        "type": "string"
      },
      "descEn": {
        "type": "string"
      },
      "civs": {
        "type": "array",
        "items": {
          "$ref": "common.defs.json#/$defs/nonEmptyString"
        }
      },
      "bz": {
        "type": "string"
      },
      "ben": {
        "type": "string"
      },
      "py": {
        "type": "string",
        "pattern": "^[a-z]*$"
      },
      "pyi": {
        "type": "string",
        "pattern": "^[a-z]*$"
      }
    },
    "required": ["id", "en", "zh", "type", "age", "b", "pic", "pre", "cost", "rt", "desc", "descEn", "civs", "bz", "ben", "py", "pyi"],
    "additionalProperties": false
  },
  "minItems": 1
}

=== linhongcun/aoe2-analyzer/src/data/techs.json
[{"id":3,"en":"Yeomen","zh":"英皇侍卫","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":450,"Wood":750},"rt":60,"desc":"步弓手和掷矛手系的射程 +1；瞭望箭塔系的攻击力 +2。","descEn":"Foot Archers and Skirmisher-line +1 range; Watch Tower-line +2 attack.","civs":["Britons"],"bz":"城堡","ben":"Castle","py":"yinghuangshiwei","pyi":"yhsw"},{"id":16,"en":"Anarchy","zh":"无政府","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":450,"Gold":250},"rt":40,"desc":"可在兵营训练侍从战士。","descEn":"Huskarls can be trained at Barracks.","civs":["Goths"],"bz":"城堡","ben":"Castle","py":"wuzhengfu","pyi":"wzf"},{"id":28,"en":"Bimaristan","zh":"穆斯林诊所","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":200,"Wood":300},"rt":50,"desc":"僧侣自动治疗附近多个单位。","descEn":"Monks passively heal multiple nearby units.","civs":["Saracens"],"bz":"城堡","ben":"Castle","py":"musilinzhensuo","pyi":"mslzs"},{"id":455,"en":"Detinets","zh":"罗斯堡垒","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":200,"Wood":400},"rt":40,"desc":"用额外的木材费用替换城堡和瞭望箭塔系 40% 的石料费用。","descEn":"Replaces 40% of Castle and Watch Tower-line stone cost with additional wood cost.","civs":["Slavs"],"bz":"城堡","ben":"Castle","py":"luosibaolei","pyi":"lsbl"},{"id":460,"en":"Atlatl","zh":"掷矛器","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":400,"Gold":350},"rt":40,"desc":"掷矛手的攻击力 +1，射程 +1。","descEn":"Skirmishers +1 attack, +1 range.","civs":["Aztecs"],"bz":"城堡","ben":"Castle","py":"zhimaoqi","pyi":"zmq"},{"id":462,"en":"Great Wall","zh":"长城","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Stone":200,"Wood":400},"rt":40,"desc":"城墙、瞭望箭塔系和炮塔的生命值 +30%。","descEn":"Walls, Watch Tower-line and Bombard Towers +30% HP.","civs":["Chinese"],"bz":"城堡","ben":"Castle","py":"changcheng","pyi":"cc"},{"id":463,"en":"Chieftains","zh":"酋长","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":600,"Gold":450},"rt":40,"desc":"步兵对骑兵的攻击力 +5，对骆驼单位的攻击力 +4。","descEn":"Infantry +5 attack vs. Cavalry, +4 vs. Camel Units.","civs":["Vikings"],"bz":"城堡","ben":"Castle","py":"qiuzhang","pyi":"qz"},{"id":464,"en":"Greek Fire","zh":"希腊之火","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":300},"rt":40,"desc":"喷火船的射程 +1；德罗蒙战舰和炮塔的爆炸范围增加。","descEn":"Fire Ships +1 range; Dromons and Bombard Towers increased blast radius.","civs":["Byzantines"],"bz":"城堡","ben":"Castle","py":"xilazhihuo","pyi":"xlzh"},{"id":482,"en":"Stronghold","zh":"堡垒","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":200},"rt":30,"desc":"城堡和瞭望箭塔系的攻击速度 +33%，城堡能治疗 7 格范围内的盟军步兵。","descEn":"Castles and Watch Tower-line attack +33% faster; Castles heal allied Infantry in a 7 tile radius.","civs":["Celts"],"bz":"城堡","ben":"Castle","py":"baolei","pyi":"bl"},{"id":483,"en":"Marauders","zh":"掠夺者","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":200,"Wood":300},"rt":40,"desc":"答刺罕骑兵可以在马厩训练。","descEn":"Tarkans can be trained at Stables.","civs":["Huns"],"bz":"城堡","ben":"Castle","py":"lveduozhe","pyi":"ldz"},{"id":484,"en":"Yasama","zh":"射箭孔","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Wood":300},"rt":40,"desc":"瞭望箭塔系可发射额外的箭矢。","descEn":"Watch Tower-line fires additional arrows.","civs":["Japanese"],"bz":"城堡","ben":"Castle","py":"shejiankong","pyi":"sjk"},{"id":485,"en":"Hul'che Javelineers","zh":"胡尔切掷矛兵","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Gold":300},"rt":40,"desc":"掷矛手可额外投掷一支长矛。","descEn":"Skirmishers fire an additional projectile.","civs":["Mayans"],"bz":"城堡","ben":"Castle","py":"huerqiezhimaobing","pyi":"heqzmb"},{"id":486,"en":"Eupseong","zh":"邑城","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Wood":300},"rt":40,"desc":"瞭望箭塔系的射程 +2。","descEn":"Watch Tower-line +2 range.","civs":["Koreans"],"bz":"城堡","ben":"Castle","py":"yicheng","pyi":"yc"},{"id":487,"en":"Nomads","zh":"游牧","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":150,"Wood":300},"rt":40,"desc":"房屋被摧毁后不会减少人口空间。","descEn":"Lost Houses do not decrease population space.","civs":["Mongols"],"bz":"城堡","ben":"Castle","py":"youmu","pyi":"ym"},{"id":488,"en":"Kamandaran","zh":"波斯步弓手","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":400,"Gold":300},"rt":40,"desc":"生产弓兵系消耗额外木材，而不消耗黄金。","descEn":"Archer-line gold cost replaced by additional wood cost.","civs":["Persians"],"bz":"城堡","ben":"Castle","py":"bosibugongshou","pyi":"bsbgs"},{"id":489,"en":"Ironclad","zh":"重装甲","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":350,"Wood":400},"rt":60,"desc":"攻城武器的近战护甲 +4。","descEn":"Siege Weapons +4 melee armor.","civs":["Teutons"],"bz":"城堡","ben":"Castle","py":"zhongzhuangjia","pyi":"zzj"},{"id":491,"en":"Sipahi","zh":"西帕希骑兵","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":350,"Gold":150},"rt":60,"desc":"骑射手的生命值 +20。","descEn":"Mounted Archers +20 HP.","civs":["Turks"],"bz":"城堡","ben":"Castle","py":"xipaxiqibing","pyi":"xpxqb"},{"id":492,"en":"Inquisition","zh":"宗教法庭","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":100,"Gold":300},"rt":40,"desc":"僧侣和传教士的招降速度加快；传教士的招降距离 +1。","descEn":"Monks and Missionaries convert faster; Missionaries +1 range.","civs":["Spanish"],"bz":"城堡","ben":"Castle","py":"zongjiaofating","pyi":"zjft"},{"id":499,"en":"Silk Road","zh":"丝绸之路","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":250},"rt":60,"desc":"贸易单位费用 -50%。","descEn":"Trade Units cost -50%.","civs":["Italians"],"bz":"城堡","ben":"Castle","py":"sichouzhilu","pyi":"sczl"},{"id":506,"en":"Grand Trunk Road","zh":"大干道","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Wood":200},"rt":40,"desc":"所有黄金收入速度 +10%；市场交易费用降至 10%。","descEn":"All gold income +10% faster; Market trading fee reduced to 10%.","civs":["Hindustanis"],"bz":"城堡","ben":"Castle","py":"dagandao","pyi":"dgd"},{"id":514,"en":"Corvinian Army","zh":"科维尼安军队","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":200,"Gold":300},"rt":40,"desc":"生产马扎尔骠骑消耗额外食物，而不消耗黄金。","descEn":"Magyar Huszar gold cost is replaced by additional food cost.","civs":["Magyars"],"bz":"城堡","ben":"Castle","py":"keweinianjundui","pyi":"kwnajd"},{"id":516,"en":"Andean Sling","zh":"安第斯弹弓","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":200,"Gold":300},"rt":40,"desc":"掷矛手和投石手无最小射程；投石手攻击力 +1。","descEn":"Skirmishers and Slingers no minimum range; Slingers +1 attack.","civs":["Incas"],"bz":"城堡","ben":"Castle","py":"andisidangong","pyi":"adsdg"},{"id":574,"en":"Royal Heirs","zh":"龙脉","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Gold":300},"rt":40,"desc":"弯刀勇士和骆驼骑兵受到骑兵单位的伤害 -3。","descEn":"Shotel Warriors and Camel Riders receive -3 damage from Mounted Units.","civs":["Ethiopians"],"bz":"城堡","ben":"Castle","py":"longmai","pyi":"lm"},{"id":576,"en":"Tigui","zh":"蛮王","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":200,"Wood":300},"rt":40,"desc":"城镇中心无驻扎单位亦能自动射箭。","descEn":"Town Centers fire arrows without garrison.","civs":["Malians"],"bz":"城堡","ben":"Castle","py":"manwang","pyi":"mw"},{"id":578,"en":"Kasbah","zh":"土堡","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":250},"rt":40,"desc":"团队的城堡训练速度 +25%。","descEn":"Team Castles work +25% faster.","civs":["Berbers"],"bz":"城堡","ben":"Castle","py":"tubao","pyi":"tb"},{"id":622,"en":"Tusk Swords","zh":"獠牙剑","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":450,"Wood":300},"rt":40,"desc":"象兵的攻击力 +3。","descEn":"Battle Elephants +3 attack.","civs":["Khmer"],"bz":"城堡","ben":"Castle","py":"liaoyajian","pyi":"lyj"},{"id":624,"en":"Thalassocracy","zh":"海上霸主","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Gold":300},"rt":40,"desc":"码头升级为巨港。","descEn":"Docks are upgraded to Harbors.","civs":["Malay"],"bz":"城堡","ben":"Castle","py":"haishangbazhu","pyi":"hsbz"},{"id":627,"en":"Manipur Cavalry","zh":"曼尼普尔马","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":300,"Gold":300},"rt":40,"desc":"骑兵对远程士兵的攻击力 +4。","descEn":"Cavalry +4 attack vs. Ranged Soldiers.","civs":["Burmese"],"bz":"城堡","ben":"Castle","py":"mannipuerma","pyi":"mnpem"},{"id":628,"en":"Chatras","zh":"宝伞","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":250},"rt":40,"desc":"象兵的生命值 +100。","descEn":"Battle Elephants +100 HP.","civs":["Vietnamese"],"bz":"城堡","ben":"Castle","py":"baosan","pyi":"bs"},{"id":685,"en":"Stirrups","zh":"马镫","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":400,"Gold":200},"rt":35,"desc":"骑兵的攻击速度 +33%。","descEn":"Cavalry attacks +33% faster.","civs":["Bulgarians"],"bz":"城堡","ben":"Castle","py":"madeng","pyi":"md"},{"id":687,"en":"Silk Armor","zh":"丝护甲","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Gold":300,"Wood":400},"rt":40,"desc":"斥候骑兵系、草原枪兵和骑射手近战护甲 +1/远程护甲 +1。","descEn":"Scout Cavalry-line, Steppe Lancers and Cavalry Archers +1 melee/+1 pierce armor.","civs":["Tatars"],"bz":"城堡","ben":"Castle","py":"sihujia","pyi":"shj"},{"id":689,"en":"Steppe Husbandry","zh":"大草原畜牧","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":200,"Wood":300},"rt":40,"desc":"斥候骑兵系、草原枪兵和骑射手的训练速度 +100%。","descEn":"Scout Cavalry-line, Steppe Lancers and Cavalry Archers train +100% faster.","civs":["Cumans"],"bz":"城堡","ben":"Castle","py":"dacaoyuanxumu","pyi":"dcyxm"},{"id":691,"en":"Hill Forts","zh":"山城堡","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":250,"Gold":250},"rt":40,"desc":"城镇中心的射程 +3。","descEn":"Town Centers +3 range.","civs":["Lithuanians"],"bz":"城堡","ben":"Castle","py":"shanchengbao","pyi":"scb"},{"id":754,"en":"Burgundian Vineyards","zh":"勃艮第葡萄园","type":"UniqueTech","age":3,"b":82,"pic":33,"pre":null,"cost":{"Food":400,"Gold":300},"rt":45,"desc":"农夫不仅能产生食物，还能缓慢地产生黄金。","descEn":"Farmers slowly generate gol
